### ISSUE TITLE
NaN handling

### ISSUE THREAD

**Issue by micsthepick** [VisualCodeBase/CodeBase#13]
I have a piece of code that looks like this:
```
bend = bend + correct * (bendraw - bend);
```

somewhere along the way, I think that bend is becoming NaN, and staying so, since nothing assigns to it, except the above expression, which is a self referential assignment.

ReaJS at the least is a little inconsistent with how it handles NaN. If you have a long expression, and something is a NaN in that expression, it gets passed to the next part of the expression, but every time a NaN gets stored, it is handled by replacment with 0. 

Keep in mind that NaN is only what I'm expecting, perhaps it's some other floating point nonsense like -0.0 or +infinity or -infinity,

currently, it looks like this compiler suite has little or no NaN handling.

**Comment by VisualCodeBase** [comment]
in the past i wrote some unpublished code for nan handling at the end of the processaudio function
but i'm not sure it is needed, as i think this is a gcc and a user thing to handle.
if you have any thought what pvf should do about, i'll be glad to listen.

**Comment by micsthepick** [comment]
you could have a toggleable option to enable handling, and then for each assignment, convert NaN to 0 before storing? I think that's how ReaJS handles it, approximately.

**Comment by micsthepick** [comment]
really all I need to know is how to handle the NaN in this one case, would there be a function to do that?

**Comment by VisualCodeBase** [comment]
i see.
you mean for each assignment to generate a function call which will check for nan.
if so, it won't be soon.
but the user (you in this case)
can do this where ever it needs to.
codebase support "fperror" to represent nan
but you cannot use it in neutron since it would be treated as an undeclared yet variable.
this i can support, by option, if you use fperror, not convert it to a variable.
until then you can try use global(), this should prevent the auto variable declaration
something like this:
function myAssignment(a,b) global() (
  b==fperror ? a = 0 : a = b;
);

i'll be back in a day or two. cheers

**Comment by micsthepick** [comment]
yes, but wouldn't fperr return false when compared against itself?

**Comment by VisualCodeBase** [comment]
sorry , like this:
function myAssignment(a,b) global() (
fperror(b) ? a = 0 : a = b;
);

**Comment by micsthepick** [comment]
either way, fperror is not defined according to the g++ compiler, so clearly the cb compiler is not replacing it correctly, but I had an idea, since fperror is actually not comparable to itself, maybe I can compare the variable against itself, and set to zero if invalid value. Looks like that fixes the issue I've had.
